export const loggedInUser = [
    {name: 'John Travolta', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-9.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
]

export const chats = [
    {name: 'John Travolta', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-9.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Brad Pitt', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-1.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Leonardo DiCaprio', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-7.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
]


export const contacts = [
    {name: 'John Travolta', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-9.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Brad Pitt', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-1.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Leonardo DiCaprio', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-7.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'John Travolta', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-9.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Brad Pitt', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-1.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
    {name: 'Leonardo DiCaprio', message: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 20', image: 'profile-7.jpg', country: 'New York City, USA', phone: '+32 19 23 62 24 34', email: 'john.travolta@gmail.com', gender: 'Male', designation: 'Software Engineer'},
]